### ISSUE TITLE
Separate critic review process to new call

### ISSUE THREAD

**Issue by cbattlegear** [Battlecabbage-Media/media-generator#8]
To allow llm to be more creative (and have more variety of critic reviews) do a second call to LLM to review the movie and have different styles/types of reviewers

**Comment by nilopmsft** [comment]
Done on this commit 656ac40588d95f6981e5f6885f3e2bc6e67d0264 Still some potential improvements to come on the completed object formatting but currently done as a separate call from the movie creation.
